iKONadmin/app/routes.py
from flask import render_template, redirect, url_for, request, Blueprint, Response, jsonify, make_response, abort
from flask_login import current_user, login_user, logout_user, login_required
from .forms import LoginForm, DeployForm
from .models import User, AdminDeploy, Deployment, DeployLocation, Script, db_session, AdminProject
from .utils import *
import re
import json
from datetime import datetime
from pytz import timezone

kon = Blueprint('kon', __name__)
ERROR_JSON = {"error": "Invalid request."}


@kon.route('/', methods=['GET', 'POST'])
@kon.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    msg = request.args.get('msg', '')
    all_deployments = []
    # get all deployments for current user, name and entry code
    deployments = get_admin_deploys()
    for deploy_id in deployments:
        deployment = db_session.query(Deployment).filter_by(deploymentid=deploy_id).first()
        all_deployments.append(deployment)

    # get admin project id
    proj_dict = dict()
    for d in all_deployments:
        proj_id = d.admin_project
        if proj_dict.get(proj_id, None) is None:
            proj_dict[proj_id] = [d]
        else:
            ds = proj_dict[proj_id]
            ds.append(d)
            proj_dict[proj_id] = ds

    # list of lists of deployments separated by project ids
    proj_name_lst = list()
    proj_deploy_lst = list()
    for p in proj_dict.keys():
        proj = db_session.query(AdminProject).filter_by(project_id=p).first()
        proj_name_lst.append(proj.project_name)
        proj_deploy_lst.append(proj_dict[p])

    # return render_template('admin.html', deployments=all_deployments, msg=msg)
    return render_template('admin.html', proj_name_lst=proj_name_lst, proj_deploy_lst=proj_deploy_lst, msg=msg)


@kon.route('/dashboard/<deploy_id>#all', methods=['GET', 'POST'])
@login_required
def dashboardall(deploy_id):
    # redirect back if the deployment is not admined by the current user
    if int(deploy_id) not in get_admin_deploys():
        abort(403)

    data = dict()  # all data

    # get deployment by deploymentid
    deployment = db_session.query(Deployment).filter_by(deploymentid=deploy_id).first()
    data['deploy_name'] = deployment.deploymentname

    # overview statistics
    unique_numbers = getUniqueUserNumber(deploy_id)
    data['unique_numbers'] = unique_numbers
    if unique_numbers == 0:
        return render_template('dashboardall.html', data=data, has_user=False, deploy_id=deploy_id)

    total_responses = getTotalResponses(deploy_id)
    data['avg_responses'] = round(total_responses / unique_numbers, 2)
    max_year, min_year = getYearSpan(deployment.sat_source, deployment.station_source)
    data['num_comparison'] = (max_year - min_year + 1) ** 2

    # top players by responses bar chart
    top_resp_users, top_resp_num = getTopUserResponse(deploy_id)
    data['top_response_bar'] = top_resp_num
    data['top_response_bar_user'] = top_resp_users

    # demographic statistics
    player_ages = getAges(deploy_id)
    player_genders = getGenders(deploy_id)
    player_income = getIncomes(deploy_id)
    player_loc, player_loc_cnt = getLocations(deploy_id)
    data['age_player_bar'] = player_ages
    data['gender_player_pie'] = player_genders
    data['income_player_bar'] = player_income
    data['location_player_pie'] = player_loc
    data['location_player_pie_cnt'] = player_loc_cnt

    # top players by scores bar chart
    all_users_by_score, all_scores = getScores(deploy_id)
    data['low_score'] = min(list(filter(lambda s: s != 0, all_scores)))
    data['avg_score'] = sum(all_scores) // len(all_scores)
    data['high_score'] = max(all_scores)
    top_scores = all_scores[:10]
    top_score_users = all_users_by_score[:10]
    top_scores.reverse()
    top_score_users.reverse()
    data['score_player_bar'] = top_scores
    data['score_player_bar_user'] = top_score_users

    # referral bar chart
    all_referrers, all_referee_num = getUserReferrals(deploy_id)
    total_referee_num = sum(all_referee_num)
    data['player_referred'] = total_referee_num
    data['player_referred_percent'] = round((total_referee_num / unique_numbers) * 100, 2)
    top_referrers = all_referrers[:10]
    top_referee_num = all_referee_num[:10]
    top_referrers.reverse()
    top_referee_num.reverse()
    data['referral_player_bar'] = top_referee_num
    data['referral_player_bar_user'] = top_referrers

    # year comparison heat map
    year_comparisons = getYearComparisons(deploy_id)
    year_comparisons_data = []
    all_years = list(range(min_year, max_year+1))
    for i in all_years:
        for j in all_years:
            num_resp = year_comparisons.get((i, j), 0)
            year_comparisons_data.append(num_resp)
    data['year_comparison_years'] = all_years
    data['year_comparison_comparisons'] = year_comparisons_data

    return render_template('dashboardall.html', data=data, has_user=True, deploy_id=deploy_id)


@kon.route('/dashboard/<deploy_id>#after', methods=['GET', 'POST'])
@login_required
def dashboardafter(deploy_id):
    # redirect back if the deployment is not admined by the current user
    if int(deploy_id) not in get_admin_deploys():
        abort(403)

    data = dict()  # data After start date

    # get deployment by deploymentid
    deployment = db_session.query(Deployment).filter_by(deploymentid=deploy_id).first()
    # get the start time of the deployment
    tz = timezone('EST')
    start_date_time = datetime.combine(deployment.start_date, datetime.min.time(), tz)

    data['deploy_name'] = deployment.deploymentname

    # overview statistics
    unique_numbers = getUniqueUserNumberAfter(deploy_id, start_date_time)
    data['unique_numbers'] = unique_numbers
    if unique_numbers == 0:
        return render_template('dashboardafter.html', data=data, has_user_after=False, deploy_id=deploy_id)

    total_responses = getTotalResponsesAfter(deploy_id, start_date_time)
    data['avg_responses'] = round(total_responses / unique_numbers, 2)
    max_year, min_year = getYearSpan(deployment.sat_source, deployment.station_source)
    data['num_comparison'] = (max_year - min_year + 1) ** 2

    # top players by responses bar chart
    top_resp_users, top_resp_num = getTopUserResponseAfter(deploy_id, start_date_time)
    data['top_response_bar'] = top_resp_num
    data['top_response_bar_user'] = top_resp_users

    # demographic statistics
    player_ages = getAgesAfter(deploy_id, start_date_time)
    player_genders = getGendersAfter(deploy_id, start_date_time)
    player_income = getIncomesAfter(deploy_id, start_date_time)
    player_loc, player_loc_cnt = getLocationsAfter(deploy_id, start_date_time)
    data['age_player_bar'] = player_ages
    data['gender_player_pie'] = player_genders
    data['income_player_bar'] = player_income
    data['location_player_pie'] = player_loc
    data['location_player_pie_cnt'] = player_loc_cnt

    # top players by scores bar chart
    all_users_by_score, all_scores = getScoresAfter(deploy_id, start_date_time)
    data['low_score'] = min(list(filter(lambda s: s != 0, all_scores)))
    data['avg_score'] = sum(all_scores) // len(all_scores)
    data['high_score'] = max(all_scores)
    top_scores = all_scores[:10]
    top_score_users = all_users_by_score[:10]
    top_scores.reverse()
    top_score_users.reverse()
    data['score_player_bar'] = top_scores
    data['score_player_bar_user'] = top_score_users

    # referral bar chart
    all_referrers, all_referee_num = getUserReferralsAfter(deploy_id, start_date_time)
    total_referee_num = sum(all_referee_num)
    data['player_referred'] = total_referee_num
    data['player_referred_percent'] = round((total_referee_num / unique_numbers) * 100, 2)
    top_referrers = all_referrers[:10]
    top_referee_num = all_referee_num[:10]
    top_referrers.reverse()
    top_referee_num.reverse()
    data['referral_player_bar'] = top_referee_num
    data['referral_player_bar_user'] = top_referrers

    # year comparison heat map
    year_comparisons = getYearComparisonsAfter(deploy_id, start_date_time)
    year_comparisons_data = []
    all_years = list(range(min_year, max_year+1))
    for i in all_years:
        for j in all_years:
            num_resp = year_comparisons.get((i, j), 0)
            year_comparisons_data.append(num_resp)
    data['year_comparison_years'] = all_years
    data['year_comparison_comparisons'] = year_comparisons_data

    return render_template('dashboardafter.html', data=data, has_user_after=True, deploy_id=deploy_id)


@kon.route('/responses_download/<deploy_code>', methods=['GET', 'POST'])
@login_required
def responses_download(deploy_code):
    # get deployment info by entry code (input arg)
    d = db_session.query(Deployment).filter_by(entry_code=deploy_code).first()

    # redirect back if the deployment is not admined by the current user
    if int(d.deploymentid) not in get_admin_deploys():
        abort(403)

    csv = getResponsesCSV(d.deploymentid)
    filename = d.deploymentname.replace(' ', '_')
    header_content = 'attachment; filename=%s.csv' % filename
    return Response(
        csv,
        mimetype='text/csv',
        headers={'Content-disposition': header_content})


@kon.route('/edit/<deploy_code>', methods=['GET', 'POST'])
@login_required
def edit(deploy_code):
    update_msg = ''
    # return to deployment table if cancel clicked
    if 'cancel' in request.form:
        return redirect(url_for('kon.admin', msg=update_msg))
    # number of rows for location list
    num_locations = 1
    deploy_form = DeployForm(request.form)
    # get deployment info by entry code (input arg)
    d = db_session.query(Deployment).filter_by(entry_code=deploy_code).first()
    deploy_id = d.deploymentid
    deployment_project_name = getProjectNameById(d.admin_project)

    # redirect back if the deployment is not admined by the current user
    if int(deploy_id) not in get_admin_deploys():
        abort(403)

    # get location list

iKONadmin/app/templates/admin.html
{% extends "base.html" %}

{% block title %} Deployments {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <!-- [ Hover-table ] start -->
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Deployments</h5>
                                <span class="d-block m-t-5">Click on a deployment name to view or edit</span>
                            </div>
                            <div class="card-block table-border-style">
                                <h6><i>{{ msg }}</i></h6>
                                <br>
                                <div class="table-responsive">
                                    {% for pname in proj_name_lst %}
                                        <h5>Project <b>{{ pname }}</b></h5>
                                        <table class="table table-hover">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Deployment Name</th>
                                                    <th>Entry Code</th>
                                                    <th>Dashboard</th>
                                                    <th>User Responses</th>
                                                    <th>Language Script</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for d in proj_deploy_lst[loop.index0] %}
                                                <tr>
                                                    <th scope="row">{{ loop.index }}</th>
                                                    <td><a href="{{ url_for('kon.edit', deploy_code=d.entry_code) }}">{{ d.deploymentname }}</a></td>
                                                    <td>{{ d.entry_code }}</td>
                                                    <td><a href="{{ url_for('kon.dashboardall', deploy_id=d.deploymentid) }}">View dashboard</a></td>
                                                    <td><a href="{{ url_for('kon.responses_download', deploy_code=d.entry_code) }}">Download responses</a></td>
                                                    <td><a href="{{ url_for('kon.editor', deploy_code=d.entry_code) }}">Edit script</a></td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    {% endfor %}
                                </div>
                                <br>
                            </div>
                        </div>
                    </div>
                    <!-- [ Hover-table ] end -->
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

iKONadmin/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>
        iKON Admin
    </title>
    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 10]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
{#    <link rel="canonical" href="https://appseed.us/admin-dashboards/flask-dashboard-dattaable">#}
    
{#    <meta name="description" content="Datta Able Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />#}
{#    <meta name="keywords" content="admin templates, bootstrap admin templates, bootstrap 4, dashboard, dashboard templets, sass admin templets, html admin templates, responsive, bootstrap admin templates free download,premium bootstrap admin templates, datta able, datta able bootstrap admin template, free admin theme, free dashboard template"/>#}
{#    <meta name="author" content="CodedThemes"/>#}

    <!-- iKON icon -->
    <link rel="icon" href="../static/assets/images/ikon_icon.ico" type="image/x-icon">
    <!-- fontawesome icon -->
    <link rel="stylesheet" href="../static/assets/fonts/fontawesome/css/fontawesome-all.min.css">
    <!-- animation css -->
    <link rel="stylesheet" href="../static/assets/plugins/animation/css/animate.min.css">
    <!-- vendor css -->
    <link rel="stylesheet" href="../static/assets/css/style.css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>

    <!-- [ Pre-loader ] start -->
{#    <div class="loader-bg">#}
{#        <div class="loader-track">#}
{#            <div class="loader-fill"></div>#}
{#        </div>#}
{#    </div>#}
    
    <!-- Top Bar -->
{#    {% include 'includes/navigation.html' %}#}

    <!-- SideBar -->
    {% include 'sidebar.html' %}

    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            {% block content %}{% endblock content %}

        </div>
    </div>

    {% include 'scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>

iKONadmin/app/templates/contact.html
{% extends "base.html" %}

{% block title %} Contact {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Contact us</h5>
                            </div>
                            <div class="card-block">
                                <p>Email: <a href="mailto:ikon@iri.columbia.edu">ikon@iri.columbia.edu</a></p>
                                <p>More info: <a href="https://fist-ikon.iri.columbia.edu/info">https://fist-ikon.iri.columbia.edu/info</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

iKONadmin/app/templates/create.html
{% extends "base.html" %}

{% block title %} Create {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h5>Your new deployment</h5>
                            </div>
                            <div class="card-body">
                                <form role="form" method="post" action="">
                                    {{ form.hidden_tag() }}
                                    <h5>Basic Setting</h5>
                                    <hr>
                                    <label for="projectName">Project Names</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{form.project_name(list="pname_datalist", class="form-control", autofocus="autofocus")}}
                                                <datalist id="pname_datalist">
                                                    {% for pname in project_names %}
                                                        <option value="{{ pname }}">
                                                    {% endfor %}
                                                </datalist>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <small id="projectNameHelp" class="form-text text-muted">Please select an existing project name or input a new one. Your deployments with the same the project name will be grouped together for easier management.</small>
                                        </div>
                                    </div>
                                    <label for="deploymentName">Deployment name</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ form.deploy_name(placeholder="Your deployment name", class="form-control") }}
                                            </div>
                                        </div>
                                    </div>
                                    <label for="entryCode">Entry Code</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ form.entry_code(placeholder="Your entry code", class="form-control") }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            {% if valid_entry_code %}
                                                <small id="entryCodeHelp" class="form-text text-muted">The entry code should contain lower-case letters only without any spaces.</small>
                                            {% else %}
                                                <small id="entryCodeHelp" style="color:red;">The entry code should contain lower-case letters only and has to be unique.</small>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <label for="languagesSelect">Language</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ form.language_select(class="form-control") }}
                                            </div>
                                        </div>
                                    </div>
                                    <label for="startDate">Start Date</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ form.start_date(class="form-control") }}
                                                <small id="startDateHelp0" class="form-text text-muted">MM/DD/YYYY</small>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <small id="startDateHelp1" class="form-text text-muted">The start date is for your record only. It is not going to effect the game process.</small>
                                        </div>
                                    </div>
                                    <label for="endDate">End Date</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ form.end_date(class="form-control") }}
                                                <small id="endDateHelp0" class="form-text text-muted">MM/DD/YYYY</small>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <small id="endDateHelp1" class="form-text text-muted">Your deployment will be deactivated by the end of the selected date (23:59:59 EST).</small>
                                            <small id="endDateHelp2" class="form-text text-muted"><b>IMPORTANT</b>: Please modify the <b>"game_time"</b> message in your language script accordingly to notify the game duration.</small>
                                        </div>
                                    </div>
                                    <label for="gamificationSelect">Gamification</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ form.gamification_select(class="form-control") }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <small id="gamificationSelectHelp" class="form-text text-muted">You have the following options:</small>
                                            <small id="gamificationSelectHelp" class="form-text text-muted">- <b>Non-Gamified</b>: All players will be playing the vanilla-version iKON game (without leaderboard or response feedback).</small>
                                            <small id="gamificationSelectHelp" class="form-text text-muted">- <b>Gamified</b>: All players will be playing the gamified iKON game (including leaderboard and response matching).</small>
                                            <small id="gamificationSelectHelp" class="form-text text-muted">- <b>Semi-Gamified</b>: 50 percent of the players will be assigned the non-gamified version, while the other half will play the gamified version.</small>
                                        </div>
                                    </div>

                                    <h5>Location List</h5>
                                    <hr>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                {{ form.location_list(class="form-control", placeholder="location1\nlocation2\nlocation3", rows=4) }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <small id="locationHelp" class="form-text text-muted">Enter each location option on a new line. The last option on your list should indicate that the user is out of your desired region, i.e. if a user chooses the last option, they will be prompted to end the game.</small>
                                        </div>
                                    </div>

                                    <h5>Data Source</h5>
                                    <hr>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="satSelect">Satellite Source</label>
                                                {{ form.sat_select(class="form-control") }}
                                            </div>
                                            <div class="form-group">
                                                <label for="weaSelect">Weather Station Source</label>
                                                {{ form.wea_select(class="form-control") }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <small id="dataSourceHelp0" class="form-text text-muted">- Click on the data source name below for more information. You may use and download the existing data set in our database.</small>
                                            <small id="dataSourceHelp1" class="form-text text-muted">- To upload a new data source, please go to <a href="{{ url_for('kon.datasource') }}">Upload Data Source</a>.</small>
                                            <small id="dataSourceHelp2" class="form-text text-muted">- If you cannot provide one of the weather station or satellite data, you may select <b>BLANK(weather station)</b> or <b>BLANK(satellite)</b> as a placeholder. The data source using the empty dataset will be omitted during the game process.</small>
                                        </div>
                                    </div>
                                    <div class="accordion" id="allDataSourceInfo">
                                        <div class="form-group">
                                            <div id="headingAll">
                                                <h5 class="mb-0"><a href="#!" class="collapsed" data-toggle="collapse" data-target="#collapseAll" aria-expanded="false" aria-controls="collapseAll">More data source information</a></h5>
                                            </div>
                                            <br>
                                            <div id="collapseAll" class="collapse" aria-labelledby="headingAll" data-parent="#allDataSourceInfo">
                                                <div class="accordion" id="dataSourceInfo">
                                                    {% for s in sources %}
                                                        <div id={{ "heading" ~ (s.source_name | replace(" ", "-")) }}>
                                                            <h6 class="mb-0"><a href="#!" class="collapsed" data-toggle="collapse" data-target={{ "#collapse" ~ (s.source_name | replace(" ", "-")) }} aria-expanded="false" aria-controls={{ "collapse" ~ (s.source_name | replace(" ", "-")) }}>{{ s.source_name }}</a></h6>
                                                            <small class="form-text text-muted">{{ s.source_type }}</small>
                                                        </div>
                                                        <div id={{ "collapse" ~ (s.source_name | replace(" ", "-")) }} class="collapse" aria-labelledby={{ "heading" ~ (s.source_name | replace(" ", "-")) }} data-parent="#dataSourceInfo">
                                                            <a href="{{ url_for('kon.source_download', source_name=s.source_name) }}">Download {{ s.source_name }} data</a><br>
                                                            {{ s.description }}
                                                        </div>
                                                        <br>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <button id="create-create" type="submit" class="btn btn-primary" name="create">Create</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{#    <script src="../static/assets/js/deploy-edit.js"></script>#}
{% endblock javascripts %}

iKONadmin/app/templates/scripts.html
    <!-- Required Js -->
    <script src="../static/assets/js/vendor-all.min.js"></script>
    <script src="../static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="../static/assets/js/jquery-3.4.1.min.js"></script>
{#    <script src="../static/assets/js/pcoded.min.js"></script>#}