iKONWebVersion/app/routes.py
from flask import render_template, flash, redirect, url_for, request, jsonify, Blueprint, session
from .forms import LoginForm, RegistrationForm
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from .utils import *
from .database import *


kon = Blueprint('kon', __name__)


@kon.route('/login', methods=['GET', 'POST'])
def login():
    # if their login works and sends them to the game page
    if current_user.is_authenticated:
        return redirect(url_for('kon.game'))

    form = LoginForm()
    if form.validate_on_submit():
        user_name = form.username.data
        user_db = getUserByUsername(user_name)

        # sends error message if not logged in correctly
        if not user_db:
            flash('Invalid username')
            return redirect(url_for('kon.login'))

        user_id = getUserId(user_name)
        user_info_update(user_id)
        user = user_info_initialize(user_id)
        print("user: ", user)

        # logs in user and sends them to next page or game
        login_user(user, remember=form.remember_me.data)

        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('kon.game')
        return redirect(next_page)

    return render_template('login.html', title='Sign In', form=form)


# logout route
@kon.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('kon.game'))


# registration page route
@kon.route('/register', methods=['GET', 'POST'])
def register():
    # automatically sent to game if already logged in
    if current_user.is_authenticated:
        return redirect(url_for('kon.game'))

    form = RegistrationForm()
    if form.validate_on_submit():
        user_id = form.email.data
        user_name = form.username.data
        entry_code = form.entry_code.data[:5]
        referral_code = form.entry_code.data[5:]
        # TODO: add referral code logic
        user_deploy = getDeployByCode(entry_code)
        # if form submitted correctly then new user is created and added to database and user is sent to login
        # generate unique referral code
        user_code = generate_code(6)
        while getUserByCode(user_code):
            user_code = generate_code(6)
        insertUser(user_id, user_name, 0, user_deploy, user_code)
        # get message script file for the deployment
        script_dict = getScript(user_deploy, "web")
        flash(script_dict["register_success"])
        return redirect(url_for('kon.login'))

    return render_template('register.html', title='Register', form=form)


@kon.route('/', methods=['GET', 'POST'])
@kon.route('/game', methods=['GET', 'POST'])
@login_required
def game():
    print("(game) current_user: ", current_user)
    user_id = current_user.get_id()
    deploy_years = current_user.get_deploy_years()
    question_years = generateTwoYears(user_id, deploy_years)
    # question generated
    if question_years:
        question_year_1 = question_years[0]
        question_year_2 = question_years[1]
        deploy_users = current_user.get_deploy_users()
        script_dict = current_user.get_script_dict()

        return render_template('game.html', script_dict=script_dict,
                               users=deploy_users, year1=question_year_1, year2=question_year_2)

    # question exhausted
    # TODO: ADD


@kon.route('/button', methods=['GET', 'POST'])
def button():
    # initialize default values (for "dont know" button)
    voted = False
    satChecker = False
    stationChecker = False
    voteChecker = False
    satName = None
    stationName = None
    voteCount = None

    print("(button) CALLED")
    user_id = current_user.get_id()
    user_name = current_user.get_username()
    user_score = current_user.get_score()
    deployment_id = current_user.get_deployment()
    sat_source_name = current_user.get_sat_source_name()
    station_source_name = current_user.get_station_source_name()
    deploy_years = current_user.get_deploy_years()

    neighbor_weight = getNeighborWeights(deployment_id)
    sat_source_weight = (100 - neighbor_weight) / 2
    station_source_weight = sat_source_weight

    json_data = request.get_json()
    buttonPressed = int(json_data["button"])  # 1 for year1, 2 for year2, 3 for same, 4 for unknown
    question_year_1 = int(json_data["year1"])
    question_year_2 = int(json_data["year2"])

    if buttonPressed:
        print("buttonPressed = ", buttonPressed)
        answer = buttonPressed
        # insert user response to database
        insertResponse(user_id, question_year_1, question_year_2, answer)

        if answer != 4:  # voted
            voted = True
            points = user_score
            # get actual satellite and weather station data for each year
            sat_data_1 = getSatValue(sat_source_name, question_year_1)
            sat_data_2 = getSatValue(sat_source_name, question_year_2)
            station_data_1 = getSatValue(station_source_name, question_year_1)
            station_data_2 = getSatValue(station_source_name, question_year_2)
            # answer based on satellite and weather station data
            sat_answer = getAnswer(sat_data_1, sat_data_2)
            station_answer = getAnswer(station_data_1, station_data_2)

            # match with satellite data
            if sat_answer == answer:
                satChecker = True
                satName = sat_source_name
                points += sat_source_weight
            # match with weather station data
            if station_answer == answer:
                stationChecker = True
                stationName = station_source_name
                points += station_source_weight
            # match with other user responses in the deployment
            deploy_responses = getDeployResponses(question_year_1, question_year_2, deployment_id)
            if deploy_responses:
                responses_matched = deploy_responses.count(answer)
                voteCount = responses_matched
                if responses_matched > 0:
                    voteChecker = True
                    points += responses_matched * neighbor_weight

            # update user score
            print("updated user points: ", points)
            setUserScore(user_id, points)
            current_user.set_score(points)
            current_user.set_deploy_users(update_deploy_users(deployment_id))

            # generate two new years for the next question
            question_years = generateTwoYears(user_id, deploy_years)

            # TODO: ADD
            # if question exhausted


            question_year_1 = question_years[0]
            question_year_2 = question_years[1]

    user_score = current_user.get_score()
    deploy_users = current_user.get_deploy_users()
    script_dict = current_user.get_script_dict()

    return jsonify(script_dict=script_dict, users=deploy_users,
                   year1=question_year_1, year2=question_year_2, score=user_score, name=user_name,
                   satChecker=satChecker, stationChecker=stationChecker, voteChecker=voteChecker, voted=voted,
                   satName=satName, stationName=stationName, voteCount=voteCount)


@kon.route('/info/', defaults={'lang': None})
@kon.route('/info/<lang>')
def info(lang):
    if lang == 'es':
        doc_name = "InformationSheetSpanish"
    else:
        doc_name = "InformationSheetEnglish"
    return render_template('info.html', doc_name=doc_name)

iKONWebVersion/app/templates/base.html
<html>
    <head>
        {% if title %}
        <title>{{ title }} - iKON</title>
        {% else %}
        <title>iKON</title>
        {% endif %}
    </head>
    <body>
        <div>
            <a href="{{ url_for('kon.game') }}">Game</a>
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('kon.login') }}">Login</a>
            {% else %}
            <a href="{{ url_for('kon.logout') }}">Logout</a>
            {% endif %}
        </div>
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

iKONWebVersion/app/templates/game.html
{% extends "base.html" %}

{% block content %}
    <head>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.js"></script>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
        <script type="text/javascript" src="{{ url_for('static', filename = 'kon.js') }}"></script>
    <script> 
        users = {{users|tojson}}
    </script>
    <style>
        #question
        {
            font-size:xx-large;
            text-align: center;
            margin-top: 3%;
            margin-bottom: 3%;
        }
        button
        {
            width: 20%;
            height: 0;
            padding-bottom:4%;
        }
        #year1, #equals
        {
            margin-right: 5%;
            margin-left: 30%;
        }

        #scoreboard
        {
            margin-top:6%;
        }
        #firstplace
        {
            background-color: #33ABF9;
            outline: 1px solid black;
            font-weight: bolder;
            font-size: x-large;
        }
        .secondthird
        {
            background-color: #6EC1F8;
            outline: 1px solid black;
            font-weight:bold;
            font-size: large;
        }
        .scorers
        {
            background-color: #AEEAFF;
            outline: 1px solid black;
        }
        img
        {
            width:100%
        }
        .icon
        {
            width:10%;
            margin: 2px;
        }
        #yourscore
        {
            margin-top:3%;
            text-align: center;
            font-size: large;
        }
        .medium
        {
            font-size: large;
        }
        #scorehead
        {
            text-align: center;
            font-size: xx-large;
        }
        #header
        {
                font-weight: bold;
                background-color: lightgoldenrodyellow;
                font-size:xx-large;
                padding-top:40px;
                padding-bottom: 40px;
        }
        .hidden
        {
            visibility: hidden;
        }

        #popup-message {
            background:rgba(0,0,0,.4);
            cursor:pointer;
            display:none;
            height:100%;
            position:fixed;
            text-align:center;
            top:0;
            width:100%;
            z-index:10000;
        }
        #popup-message .helper {
            display:inline-block;
            height:100%;
            vertical-align:middle;
        }
        #popup-message > div {
            background-color: #fff;
            box-shadow: 10px 10px 60px #555;
            display: inline-block;
            height: auto;
            max-width: 551px;
            min-height: 100px;
            vertical-align: middle;
            width: 60%;
            position: relative;
            border-radius: 8px;
            padding: 15px 5%;
        }
        </style>
    </head>
    <body>
        <div id="header" class = "row justify-content-center">
            {{ script_dict["welcome"] }}{{ current_user.username }}!
        </div>

        <div id="popup-message">
            <span class="helper"></span>
            <div>
                <p>{{ script_dict["loading_message"] }}</p>
            </div>
        </div>

        <div class="container">
            <div class = "row">
                <div class = "col-md-8">
                    <div id="question">
                        {{ script_dict["question"] }}
                    </div>
                    <div id="buttons" class="row">
                        <button id="year1">{{ year1 }}</button>
                        <button id="year2">{{ year2 }}</button>
                    </div>
                    <br>
                    <div id="buttons" class = "row">
                        <button id="equals">{{ script_dict["same"] }}</button>
                        <button id="idk">{{ script_dict["dont_know"] }}</button>
                    </div>
                    <div id="yourscore">
                        <span id="points">{{ script_dict["score"] }}{{ current_user.score }}</span> {{ script_dict["points"] }}
                        <span id="rank">{{ script_dict["user_rank"] }}{{ current_user.rank }}.</span>
                    </div>
                    <br>
                    <div class="text-center medium hidden" id="match">
                        {{ script_dict["matched"] }}
                    </div>
                    <div class="text-center medium hidden" id="none">
                        {{ script_dict["no_match"] }}
                    </div>
                    <div class="row">
                        <div class="col-md-4 hidden" id="satImage">
                            <img src="../static/images/icon_satellite.svg">
                            <div class="text-center medium" id="satellite">
                            </div>
                        </div>
                        <div class="col-md-4 hidden" id = "stationImage">
                            <img src="../static/images/icon_station.svg">
                            <div class="text-center medium" id="station">
                            </div>
                        </div>
                        <div class="col-md-4 hidden" id="userImage">
                            <img src ="../static/images/icon_group_people.jpg">
                            <div class="text-center medium" id="userNumbers">
                            </div>
                        </div>
                    </div>
                </div>
                <div class = "col-md-4">
                    <div id="scorehead"> {{ script_dict["scoreboard"] }}</div>
                    <div id ="scoreboard">
                        <div id="firstplace"><img class = "icon" src ="../static/images/generic_avatar.png">USER 1</div>
                        <div class="secondthird"><img class = "icon" src ="../static/images/generic_avatar.png">USER 2</div>
                        <div class="secondthird"><img class = "icon" src ="../static/images/generic_avatar.png">USER 3</div>
                        <div class="scorers"><img class = "icon" src ="../static/images/generic_avatar.png">USER 4</div>
                        <div class="scorers"><img class = "icon" src ="../static/images/generic_avatar.png">USER 5</div>
                        <div class="scorers"><img class = "icon" src ="../static/images/generic_avatar.png">USER 6</div>
                        <div class="scorers"><img class = "icon" src ="../static/images/generic_avatar.png">USER 7</div>
                        <div class="scorers"><img class = "icon" src ="../static/images/generic_avatar.png">USER 8</div>
                        <div class="scorers"><img class = "icon" src ="../static/images/generic_avatar.png">USER 9</div>
                        <div class="scorers"><img class = "icon" src ="../static/images/generic_avatar.png">USER 10</div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endblock %}

iKONWebVersion/app/templates/info.html
{% extends "base.html" %}

{% block content %}
    <h1>iKON</h1>
    <embed src="{{ url_for('static', filename = 'docs/') }}{{doc_name}}.pdf" width="100%" height="100%">
{% endblock %}

iKONWebVersion/app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>New User? <a href="{{ url_for('kon.register') }}">Click to Register!</a></p>
{% endblock %}

iKONWebVersion/app/templates/register.html
{% extends "base.html" %}

{% block content %}
<style>
.dropbtn:hover, .dropbtn:focus {
  background-color: silver;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd}

.show {display:block;}
</style>
<script>
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
//all style and script is used for location dropdown button
</script>

    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.entry_code.label }}<br>
            {{ form.entry_code(size=10) }}<br>
            {% for error in form.entry_code.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>

{#        {{ form.location.label }}<br>#}
{#        <select name= location method="GET" action="/">#}
{#            {% for location in locations %}#}
{#            <option value= "{{location}}" SELECTED>{{location}}</option>"#}
{#            {% endfor %}#}
{#        </select>#}
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}